spring:
  application:
    name: gateway-service-zuul

server:
  port: 8888

### 我们通过网关动态路由调用服务的时候，所调用的服务context-path尽量不要设置值，用端口区分即可
### 否则对于zuul的默认路由规则，是不带path进行调用的，会出现404的错误

###  第一种配置路由
#zuul:
#  routes:
#    baidu:
#      path: /it/**
#      url: http://www.baidu.com/

### 第二种配置路由
#zuul:
#  routes:
#    api-a:
#      path: /cloud-provider-payment/**
#      serviceId: cloud-provider-payment

### 第三种配置路由
### zuul的默认路由规则是自动从配置中心获取服务实例进行调用，所以这里可以什么都不用写

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
    ## 服务器不用注册到注册中心
#    register-with-eureka: false
    ## 服务器不用区注册中心抓取注册信息
#    fetch-registry: false

