server:
  port: 83
  servlet:
    context-path: /cloud-consumer-feign-hystrix-order
spring:
  application:
    name: cloud-consumer-feign-hystrix-order
## eureka客户端配置
eureka:
  client:
    register-with-eureka: true  #将自己注册上去
    fetch-registry: true  # 是否从EurekaServer中抓取已有的注册信息，默认为ture，单节点无所谓，集群必须是false才能配置ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7000/eureka  #单机eureka
ribbon:
  readTimeout: 1
  connectTimeout: 1
