server:
  port: 8002
  servlet:
    context-path: /cloud-provider-payment
spring:
  application:
    ## 这个名称很重要，服务的注册名称，定了以后就不要乱改了
    name: cloud-provider-payment
  ##数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.122:3306/spring-cloud-alibaba?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
## mybatis依赖
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pc.entities
## eureka客户端配置
eureka:
  instance:
    instance-id: cloud-provider-payment-${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true  #将自己注册上去
    fetch-registry: true  # 是否从EurekaServer中抓取已有的注册信息，默认为ture，单节点无所谓，集群必须是false才能配置ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7000/eureka  #单机eureka
#       defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群