server:
  port: 8002
#  servlet:
#    context-path: /cloud-provider-payment

spring:
  application:
    ## 这个名称很重要，服务的注册名称，定了以后就不要乱改了
    name: cloud-provider-payment
  ##数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-cloud-alibaba?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  zipkin: #### zipkin链路追踪配置
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值介于0到1之间，1表示全部采样，对所有的请求进行统计，一般取0.5，取一半的请求进行采样
      probability: 1

## mybatis依赖
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pc.entities

## eureka客户端配置
eureka:
  instance:
    instance-id: cloud-provider-payment
    prefer-ip-address: true
    # 客户端向服务端发送心跳的时间间隔  默认30s
    lease-renewal-interval-in-seconds: 1
    # 服务端在收到最后一次心跳后等待时间上限，超时将剔除服务
    lease-expiration-duration-in-seconds: 2
    appname: cloud-provider-payment
    hostname: cloud-provider-payment
    app-group-name: cloud-provider-payment
    virtual-host-name: cloud-provider-payment
  client:
    register-with-eureka: true  #将自己注册上去
    fetch-registry: true  # 是否从EurekaServer中抓取已有的注册信息，默认为ture，单节点无所谓，集群必须是false才能配置ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7000/eureka  #单机eureka
#       defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群


