server:
  port: 7000
spring:
  application:
    name: cloud-eureka-server-single
eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    register-with-eureka: false #自己就是服务端，不需要将自己注册上去了
    fetch-registry: false # false 表示自己端就是注册中心，我的职责就是维护实例的，不需要检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 关闭自我保护机制，保证不可用服务被及时剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000