server:
  port: 7001
spring:
  application:
    name: cloud-eureka-server-cluster01
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #自己就是服务端，不需要将自己注册上去了
    fetch-registry: false # false 表示自己端就是注册中心，我的职责就是维护实例的，不需要检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/